import { FiGithub } from 'react-icons/fi'
import {
    GraphQLBadge,
    NextBadge,
    NodeBadge,
    PrismaBadge,
    RadixUIBadge,
    ReactBadge,
    TailwindBadge
} from '../components/Projects/TechBadges'
import { ProjectT } from './types'

export const projectData: ProjectT[] = [
      {
        name: 'Zevi\'s search layout',
        id: 'petpal',
        type: 'Web app',
        tagline: 'Products search ',
        tags: [<ReactBadge />, <NodeBadge />],
        imageSrc: 'https://assets-global.website-files.com/622778f0460ef2a7b46117c1/632c38d0a82442dc8dfe0f53_zevi-logo-_2_.webp',
        description:
            'A just a web-application layout that is actual task assigned by the zevi, startup company, It has functionality to search, filter and sort the data, the data is generated by the faker data.',
        links: [
            {
                link:  'https://github.com/DataRaj/Dattaraj-Task-Dec-2023-shopping-cart-zevi',
                icon: <FiGithub />,
            },
        ],
        headerLink: 'https://dattaraj-task-dec-2023-shopping-cart.netlify.app/',
    },
    {
        name: 'D-Socials',
        id: 'dsocials',
        type: 'Web app',
        tagline: 'Products search ',
        tags: [<NextBadge />, <NodeBadge />, <PrismaBadge/>, <RadixUIBadge/>],
        imageSrc: '/d-socials.png',
        description:
            'D-Socials is one of my favorite application which works like regular social media with own UI design and architecture, It comprises the NextJS and Prisma with ExpressJS and postgresql which is deployed on the vercel and heroku',
        links: [
            {
                link: 'https://github.com/DataRaj/D-Socials-fend',
                icon: <FiGithub />,
            },
        ],
        headerLink: 'https://d-socials-media-basedweb-m9yzk1v8n-datarajs-projects.vercel.app/signin' ,
    },
    {
        name: 'Food-Deli-App',
        id: 'foodely',
        type: 'Web app',
        tagline: 'Products search ',
        tags: [<NodeBadge />, <GraphQLBadge/>, <TailwindBadge/>, <ReactBadge/>],
        imageSrc: '/deli.jpg',
        description:
            'A Food-Delia-App is inspiration idea takedn from the uber eats, I simply a perfect web-app for customer service business and delivery application, designed 3 client sites (User, Delivery and Admin) It has all features as we have used in uber eats',
        links: [
            {
                link: 'https://vercel.com/datarajs-projects/d-socials-media-basedweb-app/BVAiY4tSYSDfWxTa8Lfdo5gREWxZ',
                icon: <FiGithub />,
            },
        ],
        headerLink: 'https://github.com/DataRaj/Food-Deli-App-inspired-by-Uber-Eats-Server',
    },
    {
        name:'Movie-Booking-App',
        id: 'moviebooking',
        type: 'Web app',
        tagline: 'UI and Dynamic Website',
        tags: [<ReactBadge />, <NodeBadge />, <GraphQLBadge/>, <TailwindBadge/>],
        imageSrc: './d-socials.png',
        description:
            'This is a pretty UI oriented and very fast dynamic application serves a user to get movie or show tickets online and booking tickets user friendly',
        links: [
            {
                link: 'https://vercel.com/datarajs-projects/d-socials-media-basedweb-app/BVAiY4tSYSDfWxTa8Lfdo5gREWxZ',
                icon: <FiGithub />,
            },
        ],
        headerLink: 'https://github.com/DataRaj/Movie-booking-app',
    },
    {
        name: 'Dashboard Figma to React-JS applicaition',
        id: 'dashbaord-design',
        type: 'Figma to Design',
        tagline: 'UI and react based design',
        tags: [<ReactBadge/>, <TailwindBadge/>],
        imageSrc: './dashboard-design.png',
        description: 
            'This design was actually task that was assigned by the company and I had around 3 hours to complete this task so I have completed in given time. Actually It had lot of factors like a UI design Component writing, arranging all those components and tailwindCss',
        links: [
            {
                link: 'https://github.com/DataRaj/full-stack-developer-all-tasks',
                icon: <FiGithub/>
            }
        ],
        headerLink: 'https://full-stack-developer-all-tasks.vercel.app/'
/    }

    // {
    //     name: 'PetPal',
    //     id: 'petpal',
    //     type: 'Web app',
    //     tagline: 'A pet adoption platform for animal shelters',
    //     tags: [<ReactBadge />, <DjangoBadge />, <MySQLBadge />],
    //          imageSrc: '/petpal.png',
    //     description:
    //         'A pet adoption platform for animal shelters and prospective adopters featuring an admin dashboard, a customized application process, a REST API, and a frontend built with Tailwind.',
    //     links: [
    //         {
    //             link: 'https://github.com/leowrites/PetPal',
    //             icon: <FiGithub />,
    //         },
    //     ],
    //     headerLink: 'https://github.com/leowrites/PetPal',
    // },
    // {
    //     name: 'Street Savvy',
    //     id: 'street-savvy',
    //     type: 'Web app',
    //     tagline: 'Suggests places to visit tailored using your preferences',
    //     tags: [
    //         <ReactBadge />,
    //         <TypescriptBadge />,
    //         <FirebaseBadge />,
    //         <PythonBadge />,
    //     ],
    //     imageSrc: '/street-savvy.jpg',
    //     description:
    //         'A web app that suggests places to visit in Toronto based on your preferences using a custom recommendation engine and data from the Google Places API. Submitted to UofTHacks X.',
    //     links: [
    //         {
    //             link: 'https://github.com/DataRaj/Supply-Chain-stocks-manager-system',
    //             icon: <FiGithub />,
    //         },
    //     ],
    //     headerLink: 'https://github.com/jasonfyw/street-savvy',
    // },
    // {
    //     name: 'Twitter Geo-Sentiment',
    //     id: 'twitter-geo-sentiment',
    //     type: 'Web app',
    //     tagline: 'Analyse and visualise regional sentiment on Twitter',
    //     tags: [<PythonBadge />, <ReactBadge />, <MongoBadge />],
    //     imageSrc: '/twitter-geo-sentiment.jpg',
    //     description:
    //         'A web tool allowing queries analysing and visualising regional sentiment towards given topics on Twitter during a specific time frame. A custom-trained Naive Bayes model is used to perform sentiment analysis on aggregated data.',
    //     links: [
    //         {
    //             link: 'https://github.com/jasonfyw/twitter-geo-sentiment',
    //             icon: <FiGithub />,
    //         },
    //     ],
    //     headerLink: 'https://github.com/jasonfyw/twitter-geo-sentiment',
    // },
    // {
    //     name: 'Fourier Series Animation',
    //     id: 'fourier-series',
    //     type: 'Web app',
    //     tagline:
    //         'Demonstrating the Fourier series by approximating user-inputted line drawings',
    //     tags: [<ReactBadge />, <TypescriptBadge />],
    //     imageSrc: '/fourier-series.png',
    //     description:
    //         'An interactive React web app that demonstrates how an arbitrary user-inputted line drawing can be approximated using the Fourier series. Animations are rendered by the P5 library using efficiently implemented computations.',
    //     links: [
    //         {
    //             link: 'https://github.com/jasonfyw/fourier-series',
    //             icon: <FiGithub />,
    //         },
    //         {
    //             link: 'https://jasonfyw.com/fourier-series/',
    //             icon: <FiLink />,
    //         },
    //     ],
    //     headerLink: 'https://jasonfyw.com/fourier-series/',
    // },
    // {
    //     name: 'Orbital Simulation',
    //     id: 'orbital-sim',
    //     type: 'Physics simulation',
    //     tagline:
    //         'A PyGame simulation accurately modelling planetary orbits in space',
    //     tags: [<PythonBadge />],
    //     imageSrc: '/orbital-sim.png',
    //     description:
    //         'An implementation of Newtonian physics in PyGame using positional data from the JPL Horizons database to simulate and record data on the past and future movements of celestial bodies in our solar system and beyond.',
    //     links: [
    //         {
    //             link: 'https://github.com/jasonfyw/orbital-sim',
    //             icon: <FiGithub />,
    //         },
    //     ],
    //     headerLink: 'https://github.com/jasonfyw/orbital-sim',
    // },
    // {
    //     name: 'PLISMUN',
    //     id: 'plismun',
    //     type: 'Website',
    //     tagline: 'The official website for PLISMUN',
    //     tags: [<PHPBadge />, <MySQLBadge />],
    //     imageSrc: '/plismun.jpg',
    //     description:
    //         "A platform for my high school's annual international MUN conference, built from the ground up providing a delegate application system, admin tools, analytics, and resource hub. It managed hundreds of users from dozens of countries.",
    //     links: [
    //         {
    //             link: 'https://github.com/jasonfyw/plismun',
    //             icon: <FiGithub />,
    //         },
    //         {
    //             link: 'https://plismun.com',
    //             icon: <FiLink />,
    //         },
    //     ],
    //     headerLink: 'https://plismun.com',
    // },
    // {
    //     name: 'Photography Portfolio',
    //     id: 'photography-portfolio',
    //     type: 'Website',
    //     tagline: 'A portfolio website for my photography',
    //     tags: [<ReactBadge />, <TypescriptBadge />],
    //     imageSrc: '/photography-portfolio.png',
    //     description:
    //         'A portfolio website for my photography work, built with React and Typescript and styled with ChakraUI. Features a custom-built gallery, e-commerce functionality, and 3D map integration with Mapbox.',
    //     links: [
    //         {
    //             link: 'https://photo.jasonfyw.com/',
    //             icon: <FiLink />,
    //         },
    //     ],
    // },
    // {
    //     name: 'Linky',
    //     id: 'linky',
    //     type: 'Web app',
    //     tagline: 'A modern, lightweight link shortener',
    //     tags: [
    //         <ReactBadge />,
    //         <TypescriptBadge />,
    //         <NodeBadge />,
    //         <MongoBadge />,
    //     ],
    //     imageSrc: '/linky.png',
    //     description:
    //         'A lightweight and simple to use link shortener web app with a NodeJS REST API and a frontend built with ChakraUI. Features additional functions like QR codes and alternative URL formats.',
    //     links: [
    //         {
    //             link: 'https://github.com/jasonfyw/linky',
    //             icon: <FiGithub />,
    //         },
    //         {
    //             link: 'https://lnky.to',
    //             icon: <FiLink />,
    //         },
    //     ],
    //     headerLink: 'https://lnky.to',
    // },
    // {
    //     name: 'Blogging Application',
    //     id: 'blogging-app',
    //     type: 'Web app',
    //     tagline:
    //         'Java blogging application built using CLEAN architecture and SOLID principles',
    //     tags: [<JavaBadge />],
    //     imageSrc: '/blogging-app.jpg',
    //     description:
    //         'Our group project for CSC207 - a blogging website where users can post text content and follow other accounts. Designed and built according to CLEAN architecture and SOLID principles.',
    //     links: [
    //         {
    //             link: 'https://github.com/jasonfyw/csc207-blogging-app',
    //             icon: <FiGithub />,
    //         },
    //     ],
    //     headerLink: 'https://github.com/jasonfyw/csc207-blogging-app',
    // },
    // {
    //     name: 'Breakout in MIPS',
    //     id: 'breakout-asm',
    //     type: 'Game',
    //     tagline: 'Atari Breakout implemented in MIPS Assembly for CSC258',
    //     tags: [<AssemblyBadge />],
    //     imageSrc: '/breakout-asm.png',
    //     description:
    //         'Using MIPS Assembly to implement an Atari Breakout clone with features such as game controls, multiple lives, displaying score, and more.',
    //     links: [
    //         {
    //             link: 'https://github.com/jasonfyw/csc258-project',
    //             icon: <FiGithub />,
    //         },
    //     ],
    //     headerLink: 'https://github.com/jasonfyw/csc258-project',
    // },
]
